### ISSUE TITLE
Read from stdin

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/win-clipboard#1]
Would be nicer to read from stdin instead of argv, but I couldn't figure out how. Right now I have to have a workaround in `clipboardy` because of this: https://github.com/sindresorhus/clipboardy/blob/48d5b0fbb793d4d94df532cae8f55ea9587e011c/index.js#L31-L32

// @qix- Please halp 🙏

**Comment by Qix-** [comment]
Could you explain a little more? What do you mean you're reading from argv?

**Comment by sindresorhus** [comment]
Right now I get the text to be placed on the clipboard from `argv[1]`. I want to get it from stdin instead. I want to do [this](https://github.com/sindresorhus/clipboard-cli/blob/b3f6f78a5724b8c0d07087b47eee4833774e3b85/cli.js#L17) in C.

**Comment by Qix-** [comment]
I don't have a windows box available at the moment, but [this is the first thing I would try](http://stackoverflow.com/a/21036020/510036). It's pretty analogous to how you would read full text from a file.

**Comment by sindresorhus** [comment]
@Qix- Yes, I've seen similar solutions when searching, but how can I make it accept an arbitrary sized stdin buffer? In your linked answer the size is predefined (`char buffer[16384];`). I need some kind of dynamic buffer.

**Comment by Qix-** [comment]
@sindresorhus `malloc()` and `free()`, though you shouldn't need a dynamically sized buffer. You just read the input in chunks and concat the chunks, especially since you don't know the size of the input.

**Comment by sindresorhus** [comment]
Not really completely fixed.
